/**:
  ros__parameters:
    gains:
      FFJ1: &id001
        d: 0
        i: 10
        p: 100
      FFJ2: *id001
      FFJ3: *id001
      FFJ4: *id001
      MFJ1: *id001
      MFJ2: *id001
      MFJ3: *id001
      MFJ4: *id001
      RFJ1: *id001
      RFJ2: *id001
      RFJ3: *id001
      RFJ4: *id001
      THJ1: *id001
      THJ2: *id001
      THJ4: *id001
      THJ5: *id001
      arm_1_joint:
        d: 5
        i: 1
        i_clamp: 3
        p: 3000
        torque_clamp: 60
      arm_2_joint:
        d: 5
        i: 1
        i_clamp: 3
        p: 3000
        torque_clamp: 50
      arm_3_joint:
        d: 5
        i: 1
        i_clamp: 3
        p: 3000
        torque_clamp: 50
      arm_4_joint:
        d: 5
        i: 1
        i_clamp: 3
        p: 3000
        torque_clamp: 50
      arm_5_joint:
        d: 1
        i: 0.1
        i_clamp: 3
        p: 500
        torque_clamp: 50
      arm_6_joint:
        d: 1
        i: 0.1
        i_clamp: 3
        p: 500
        torque_clamp: 50
      arm_7_joint:
        d: 1
        i: 0.1
        i_clamp: 3
        p: 500
        torque_clamp: 50
      gripper_left_finger_joint: &id002
        d: 0
        i: 0
        p: 2000
        p_gain: 2000
      gripper_right_finger_joint: *id002
      hand_index_abd_joint: &id003
        d: 0.1
        i: 0.1
        i_clamp: 1
        p: 50
      hand_index_flex_1_joint: *id003
      hand_index_flex_2_joint: *id003
      hand_index_flex_3_joint: *id003
      hand_index_joint: *id003
      hand_index_virtual_1_joint: *id003
      hand_index_virtual_2_joint: *id003
      hand_index_virtual_3_joint: *id003
      hand_little_abd_joint: *id003
      hand_little_flex_1_joint: *id003
      hand_little_flex_2_joint: *id003
      hand_little_flex_3_joint: *id003
      hand_little_virtual_1_joint: *id003
      hand_little_virtual_2_joint: *id003
      hand_little_virtual_3_joint: *id003
      hand_middle_abd_joint: *id003
      hand_middle_flex_1_joint: *id003
      hand_middle_flex_2_joint: *id003
      hand_middle_flex_3_joint: *id003
      hand_middle_virtual_1_joint: *id003
      hand_middle_virtual_2_joint: *id003
      hand_middle_virtual_3_joint: *id003
      hand_mrl_joint: *id003
      hand_ring_abd_joint: *id003
      hand_ring_flex_1_joint: *id003
      hand_ring_flex_2_joint: *id003
      hand_ring_flex_3_joint: *id003
      hand_ring_virtual_1_joint: *id003
      hand_ring_virtual_2_joint: *id003
      hand_ring_virtual_3_joint: *id003
      hand_thumb_abd_joint: *id003
      hand_thumb_flex_1_joint: *id003
      hand_thumb_flex_2_joint: *id003
      hand_thumb_flex_3_joint: *id003
      hand_thumb_joint: *id003
      hand_thumb_virtual_1_joint: *id003
      hand_thumb_virtual_2_joint: *id003
      hand_thumb_virtual_3_joint: *id003
      head_1_joint:
        d: 0
        i: 10
        i_clamp: 1.5
        p: 100
      head_2_joint:
        d: 0
        i: 10
        i_clamp: 1.5
        p: 100
      torso_lift_joint:
        d: 250
        i: 10
        i_clamp: 1.5
        p: 30000
      xtion_frame_joint:
        d: 0
        i: 0
        i_clamp: 1.5
        p: 0.5
    velocity:
      gains:
        wheel_left_joint:
          d: 0
          i: 0
          i_clamp: 1.0
          p: 30
        wheel_right_joint:
          d: 0
          i: 0
          i_clamp: 1.0
          p: 30
