/**:
  ros__parameters:
    play_motion:
      controllers:
      - arm_controller
      - head_controller
      - torso_controller
      - gripper_controller
      motions:
        close:
          joints:
          - gripper_finger_joint
          meta:
            description: Closes gripper
            name: Close Gripper
            usage: demo
          points:
          - positions:
            - 0.0
            time_from_start: 0.5
        close_gripper:
          joints:
          - gripper_finger_joint
          points:
          - positions:
            - 0.0
            time_from_start: 0.5
        close_gripper_half:
          joints:
          - gripper_finger_joint
          points:
          - positions:
            - 0.015
            time_from_start: 0.5
        close_half:
          joints:
          - gripper_finger_joint
          meta:
            description: Closes gripper halfway
            name: Close Gripper Half
            usage: demo
          points:
          - positions:
            - 0.015
            time_from_start: 0.5
        do_weights:
          joints:
          - arm_1_joint
          - arm_2_joint
          - arm_3_joint
          - arm_4_joint
          - arm_5_joint
          - arm_6_joint
          - arm_7_joint
          meta:
            description: Do weights
            name: Do Weights
            usage: demo
          points:
          - positions:
            - 1.6
            - -1.18
            - -3.16
            - 2.0
            - -1.57
            - -0.07
            - 0.0
            time_from_start: 1.0
          - positions:
            - 1.6
            - -1.48
            - -3.16
            - 1.62
            - -1.57
            - -0.2
            - 0.0
            time_from_start: 2.0
          - positions:
            - 1.6
            - -0.9
            - -3.16
            - 2.0
            - -1.57
            - 0.35
            - 0.0
            time_from_start: 4.0
          - positions:
            - 1.6
            - -1.48
            - -3.16
            - 1.62
            - -1.57
            - -0.2
            - 0.0
            time_from_start: 6.0
          - positions:
            - 1.6
            - -0.9
            - -3.16
            - 2.0
            - -1.57
            - 0.35
            - 0.0
            time_from_start: 8.0
          - positions:
            - 1.6
            - -1.48
            - -3.16
            - 1.62
            - -1.57
            - -0.2
            - 0.0
            time_from_start: 10.0
          - positions:
            - 1.6
            - -1.18
            - -3.16
            - 2.0
            - -1.57
            - -0.07
            - 0.0
            time_from_start: 12.0
        head_tour:
          joints:
          - head_1_joint
          - head_2_joint
          meta:
            description: head_tour
            name: Head Tour
            usage: demo
          points:
          - positions:
            - 0
            - 0
            time_from_start: 0.1
          - positions:
            - 0.7
            - 0
            time_from_start: 3.0
          - positions:
            - 0.7
            - 0.3
            time_from_start: 6.0
          - positions:
            - 0.7
            - -0.3
            time_from_start: 9.0
          - positions:
            - 0.7
            - 0.3
            time_from_start: 12.0
          - positions:
            - -0.7
            - 0.3
            time_from_start: 15.0
          - positions:
            - -0.7
            - -0.3
            time_from_start: 18.0
          - positions:
            - 0
            - 0
            time_from_start: 21.0
        home:
          joints:
          - torso_lift_joint
          - arm_1_joint
          - arm_2_joint
          - arm_3_joint
          - arm_4_joint
          - arm_5_joint
          - arm_6_joint
          - arm_7_joint
          meta:
            description: Go home
            name: Home
            usage: demo
          points:
          - positions:
            - 0.25
            - 0.2
            - 0.35
            - -0.2
            - 1.94
            - -1.57
            - 1.37
            - -1.58
            time_from_start: 0.5
          - positions:
            - 0.18
            - 0.2
            - -1.34
            - -0.2
            - 1.94
            - -1.57
            - 1.37
            - -1.58
            time_from_start: 4.0
          - positions:
            - 0.15
            - 0.2
            - -1.34
            - -0.2
            - 1.94
            - -1.57
            - 1.37
            - -1.58
            time_from_start: 7.0
          - positions:
            - 0.15
            - 0.2
            - -1.34
            - -0.2
            - 1.94
            - -1.57
            - 1.37
            - 0.0
            time_from_start: 9.0
        inspect_surroundings:
          joints:
          - head_1_joint
          - head_2_joint
          meta:
            description: Inspect surroundings around the robot
            name: Inspect Surroundings
            usage: demo
          points:
          - positions:
            - -1.0
            - -0.85
            time_from_start: 1.5
          - positions:
            - -1.0
            - -0.85
            time_from_start: 2.0
          - positions:
            - 1.0
            - -0.85
            time_from_start: 4.5
          - positions:
            - 1.0
            - -0.85
            time_from_start: 5.0
          - positions:
            - 0.0
            - -0.85
            time_from_start: 7.0
        offer:
          joints:
          - torso_lift_joint
          - arm_1_joint
          - arm_2_joint
          - arm_3_joint
          - arm_4_joint
          - arm_5_joint
          - arm_6_joint
          - arm_7_joint
          - gripper_finger_joint
          meta:
            description: Offer Gripper
            name: Offer Gripper
            usage: demo
          points:
          - positions:
            - 0.296
            - 1.61
            - -0.93
            - -3.14
            - 1.83
            - -1.577
            - -0.62
            - -1.577
            - 0.031
            time_from_start: 0.0
        offer_gripper:
          joints:
          - torso_lift_joint
          - arm_1_joint
          - arm_2_joint
          - arm_3_joint
          - arm_4_joint
          - arm_5_joint
          - arm_6_joint
          - arm_7_joint
          - gripper_finger_joint
          points:
          - positions:
            - 0.296
            - 1.61
            - -0.93
            - -3.14
            - 1.83
            - -1.577
            - -0.62
            - -1.577
            - 0.031
            time_from_start: 0.0
        open:
          joints:
          - gripper_finger_joint
          meta:
            description: Open gripper
            name: Open Gripper
            usage: demo
          points:
          - positions:
            - 0.031
            time_from_start: 0.5
        open_gripper:
          joints:
          - gripper_finger_joint
          points:
          - positions:
            - 0.031
            time_from_start: 0.5
        pick_from_floor:
          joints:
          - torso_lift_joint
          - arm_1_joint
          - arm_2_joint
          - arm_3_joint
          - arm_4_joint
          - arm_5_joint
          - arm_6_joint
          - arm_7_joint
          - gripper_finger_joint
          meta:
            description: Pick a shirt-like object from floor in front of the robot
            name: Pick from floor
            usage: demo
          points:
          - positions:
            - 0.226
            - 0.308
            - -0.695
            - -0.968
            - 1.582
            - 1.965
            - 0.273
            - -1.101
            - 0.031
            time_from_start: 0.0
          - positions:
            - 0.12
            - 0.809
            - -1.197
            - -1.119
            - 0.322
            - 1.96
            - -0.849
            - 0.041
            - 0.031
            time_from_start: 4.0
          - positions:
            - 0.12
            - 0.809
            - -1.197
            - -1.119
            - 0.345
            - 1.96
            - -0.849
            - 0.041
            - 0.0
            time_from_start: 6.0
          - positions:
            - 0.27
            - 0.21
            - -1.153
            - -1.538
            - 2.26
            - 1.965
            - 0.394
            - -0.082
            - 0.0
            time_from_start: 9.0
        point:
          joints:
          - gripper_finger_joint
          meta:
            description: Closes gripper to point to something
            name: Point
            usage: demo
          points:
          - positions:
            - 0.0
            time_from_start: 0.5
        pregrasp_weight:
          joints:
          - torso_lift_joint
          - arm_1_joint
          - arm_2_joint
          - arm_3_joint
          - arm_4_joint
          - arm_5_joint
          - arm_6_joint
          - arm_7_joint
          meta:
            description: Pregrasp weight
            name: Pregrasp Weight
            usage: demo
          points:
          - positions:
            - 0.1
            - 1.6
            - -1.18
            - -3.16
            - 2.0
            - -1.57
            - -0.07
            - 0.0
            time_from_start: 1.0
        prepare_grasp:
          joints:
          - torso_lift_joint
          - arm_1_joint
          - arm_2_joint
          - arm_3_joint
          - arm_4_joint
          - arm_5_joint
          - arm_6_joint
          - arm_7_joint
          meta:
            description: Prepare grasp position
            name: Prepare Grasp
            usage: demo
          points:
          - positions:
            - 0.34
            - 0.2
            - -1.34
            - -0.2
            - 1.94
            - -1.57
            - 1.37
            - -1.58
            time_from_start: 3.0
          - positions:
            - 0.34
            - 0.1
            - 0.47
            - -0.2
            - 1.56
            - -1.58
            - 0.25
            - 0.0
            time_from_start: 8.5
          - positions:
            - 0.34
            - 0.1
            - 0.47
            - -0.2
            - 1.56
            - 1.6
            - 0.25
            - 1.19
            time_from_start: 10.5
        reach_floor:
          joints:
          - torso_lift_joint
          - arm_1_joint
          - arm_2_joint
          - arm_3_joint
          - arm_4_joint
          - arm_5_joint
          - arm_6_joint
          - arm_7_joint
          meta:
            description: Reach floor
            name: Reach Floor
            usage: demo
          points:
          - positions:
            - 0.19
            - 1.6
            - -1.18
            - -3.16
            - 2.0
            - -1.57
            - -0.07
            - 0.0
            time_from_start: 1.0
          - positions:
            - 0.19
            - 1.6
            - -0.55
            - -1.35
            - 1.4
            - -1.57
            - -0.07
            - 0.0
            time_from_start: 3.0
          - positions:
            - 0.16
            - 1.6
            - -0.55
            - 0
            - 1.03
            - -1.57
            - -0.07
            - 0.0
            time_from_start: 7.0
        reach_max:
          joints:
          - torso_lift_joint
          - arm_1_joint
          - arm_2_joint
          - arm_3_joint
          - arm_4_joint
          - arm_5_joint
          - arm_6_joint
          - arm_7_joint
          meta:
            description: Reach max
            name: Reach Max
            usage: demo
          points:
          - positions:
            - 0.1
            - 1.6
            - -1.18
            - -3.16
            - 2.0
            - -1.57
            - -0.07
            - 0.0
            time_from_start: 1.0
          - positions:
            - 0.35
            - 0.9
            - 0.68
            - -3.16
            - 1.1
            - 2.05
            - 1.0
            - 0.0
            time_from_start: 4.0
          - positions:
            - 0.35
            - 0.9
            - 1.0
            - -3.45
            - 0.45
            - 2.05
            - 1.0
            - 0.0
            time_from_start: 7.0
        shake_hands:
          joints:
          - gripper_finger_joint
          - torso_lift_joint
          - arm_1_joint
          - arm_2_joint
          - arm_3_joint
          - arm_4_joint
          - arm_5_joint
          - arm_6_joint
          - arm_7_joint
          meta:
            description: shake_hands
            name: Shake Hands
            usage: demo
          points:
          - positions:
            - 0.031
            - 0.296
            - 1.61
            - -0.93
            - -3.14
            - 1.83
            - -1.577
            - -0.53
            - -1.577
            time_from_start: 0.0
          - positions:
            - 0.025
            - 0.296
            - 1.61
            - -0.93
            - -3.14
            - 1.83
            - -1.577
            - -0.53
            - -1.577
            time_from_start: 5.0
          - positions:
            - 0.025
            - 0.296
            - 1.61
            - -0.93
            - -3.14
            - 1.4
            - -1.577
            - -0.2
            - -1.577
            time_from_start: 6.0
          - positions:
            - 0.025
            - 0.296
            - 1.61
            - -0.93
            - -3.14
            - 1.83
            - -1.577
            - -0.53
            - -1.577
            time_from_start: 7.0
          - positions:
            - 0.025
            - 0.296
            - 1.61
            - -0.93
            - -3.14
            - 1.4
            - -1.577
            - -0.2
            - -1.577
            time_from_start: 8.0
          - positions:
            - 0.025
            - 0.296
            - 1.61
            - -0.93
            - -3.14
            - 1.83
            - -1.577
            - -0.53
            - -1.577
            time_from_start: 9.0
          - positions:
            - 0.031
            - 0.296
            - 1.61
            - -0.93
            - -3.14
            - 1.83
            - -1.577
            - -0.53
            - -1.577
            time_from_start: 11.0
        unfold_arm:
          joints:
          - torso_lift_joint
          - arm_1_joint
          - arm_2_joint
          - arm_3_joint
          - arm_4_joint
          - arm_5_joint
          - arm_6_joint
          - arm_7_joint
          meta:
            description: unfold_arm
            name: Unfold arm
            usage: demo
          points:
          - positions:
            - 0.3
            - 0.21
            - 0.35
            - -0.2
            - 0.8
            - -1.57
            - 1.37
            - 0.0
            time_from_start: 0.5
          - positions:
            - 0.3
            - 0.21
            - -0.2
            - -2.2
            - 1.15
            - -1.57
            - 0.2
            - 0.0
            time_from_start: 6.0
        wave:
          joints:
          - arm_1_joint
          - arm_2_joint
          - arm_3_joint
          - arm_4_joint
          - arm_5_joint
          - arm_6_joint
          - arm_7_joint
          meta:
            description: wave
            name: Wave
            usage: demo
          points:
          - positions:
            - 0.09
            - -0.679638896132783
            - -3.1087325315620733
            - 2.0882339360702575
            - -1.1201172410014792
            - -0.031008601325809293
            - -2.0
            time_from_start: 0.0
          - positions:
            - 0.09
            - -0.7354151774072313
            - -2.939624246421942
            - 1.8341256735249563
            - -1.1201355028397157
            - -0.031008601325809293
            - -2.0
            time_from_start: 1.0
          - positions:
            - 0.09
            - -0.7231278283145929
            - -2.9385504456273295
            - 2.18
            - -1.1201355028397157
            - -0.031008601325809293
            - -2.04
            time_from_start: 2.0
          - positions:
            - 0.09
            - -0.7354151774072313
            - -2.939624246421942
            - 1.8341256735249563
            - -1.1201355028397157
            - -0.031008601325809293
            - -2.0
            time_from_start: 3.0
